In [1]:
import pandas as pd

In [2]:
raw_df = pd.read_csv("../data/source/raw_data.csv")
raw_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
1495,536544,22075,6 RIBBONS ELEGANT CHRISTMAS,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1496,536544,22076,6 RIBBONS EMPIRE,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1497,536544,22077,6 RIBBONS RUSTIC CHARM,3,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1498,536544,22080,RIBBON REEL POLKADOTS,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1499,536544,22081,RIBBON REEL FLORA + FAUNA,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom

In [3]:
# create a copy of raw_df so that the raw data remains unchanged
df = raw_df.copy()
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [5]:
df["InvoiceNo"]

0       536365
1       536365
2       536365
3       536365
4       536365
         ...
1495    536544
1496    536544
1497    536544
1498    536544
1499    536544
Name: InvoiceNo, Length: 1500, dtype: object

In [6]:
# invoiceNo's with characters
df[df["InvoiceNo"].astype(str).str.contains(r"[A-Za-z]")]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom

In [7]:
# quantity column has negatives
df[df["Quantity"] <= 0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom

In [8]:
# replace them with their absolute value
df["Quantity"] = df["Quantity"].abs()

In [9]:
# now this returns nothing
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [10]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [11]:
df.isna().sum()

InvoiceNo       0
StockCode       0
Description     1
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     58
Country         0
dtype: int64

In [12]:
df[df["CustomerID"].isna()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2010-12-01 14:32:00,2.98,NaN,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,2010-12-01 14:32:00,5.91,NaN,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1462,536544,21874,GIN AND TONIC MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1463,536544,21879,HEARTS GIFT TAPE,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1464,536544,21884,CAKES AND BOWS GIFT TAPE,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1465,536544,21888,BINGO SET,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1466,536544,21889,WOODEN BOX OF DOMINOES,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1467,536544,21892,TRADITIONAL WOODEN CATCH CUP GAME,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1468,536544,21894,POTTING SHED SEED ENVELOPES,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1469,536544,21911,GARDEN METAL SIGN,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1470,536544,21912,VINTAGE SNAKES & LADDERS,3,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1471,536544,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1472,536544,21914,BLUE HARMONICA IN BOX,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1473,536544,21915,RED HARMONICA IN BOX,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1474,536544,21922,UNION STRIPE WITH FRINGE HAMMOCK,2,2010-12-01 14:32:00,16.98,NaN,United Kingdom
1475,536544,21928,JUMBO BAG SCANDINAVIAN PAISLEY,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1476,536544,21935,SUKI SHOULDER BAG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1477,536544,21942,SKULLS DESIGN FLANNEL,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1478,536544,21944,KITTENS DESIGN FLANNEL,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1479,536544,21949,SET OF 6 STRAWBERRY CHOPSTICKS,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1480,536544,21975,PACK OF 60 DINOSAUR CAKE CASES,1,2010-12-01 14:32:00,1.28,NaN,United Kingdom
1481,536544,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,2010-12-01 14:32:00,1.28,NaN,United Kingdom
1482,536544,21982,PACK OF 12 SUKI TISSUES,1,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1483,536544,21990,MODERN FLORAL STATIONERY SET,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1484,536544,21991,BOHEMIAN COLLAGE STATIONERY SET,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1485,536544,21992,VINTAGE PAISLEY STATIONERY SET,6,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1486,536544,21993,FLORAL FOLK STATIONERY SET,4,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1487,536544,22037,ROBOT BIRTHDAY CARD,1,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1488,536544,22043,CHRISTMAS CARD SCREEN PRINT,1,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1489,536544,22064,PINK DOUGHNUT TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1490,536544,22065,CHRISTMAS PUDDING TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1491,536544,22067,CHOC TRUFFLE GOLD TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1492,536544,22068,BLACK PIRATE TREASURE CHEST,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1493,536544,22069,BROWN PIRATE TREASURE CHEST,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1494,536544,22071,SMALL WHITE RETROSPOT MUG IN BOX,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1495,536544,22075,6 RIBBONS ELEGANT CHRISTMAS,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1496,536544,22076,6 RIBBONS EMPIRE,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1497,536544,22077,6 RIBBONS RUSTIC CHARM,3,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1498,536544,22080,RIBBON REEL POLKADOTS,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1499,536544,22081,RIBBON REEL FLORA + FAUNA,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom

In [13]:
df["CustomerID"].isna().sum()

np.int64(58)

In [14]:
df[df["InvoiceNo"]==536414]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [15]:
df["CustomerID"].isna().mean() * 100

np.float64(3.8666666666666667)

In [16]:
# removing CustomerID = NaN
df = df.dropna(subset=["CustomerID"])

In [17]:
# df now doesn't contain customerID = NaN
df["CustomerID"].isna().sum()

np.int64(0)

In [18]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [19]:
df["CustomerID"] = df["CustomerID"].astype(int)

In [20]:
# just to be sure
df.loc[:, "Quantity"] = df["Quantity"].astype(int)

In [21]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID       int64
Country         object
dtype: object

In [22]:
df["CustomerID"]

0       17850
1       17850
2       17850
3       17850
4       17850
        ...
1438    16456
1439    16456
1440    16456
1441    17841
1442    17841
Name: CustomerID, Length: 1442, dtype: int64

In [23]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [24]:
# no missing values anymore
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [25]:
# convert dates to datetime to handle them better
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [26]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

In [27]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897,United Kingdom
1061,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012,United Kingdom
1067,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012,United Kingdom
1140,536528,22865,HAND WARMER OWL DESIGN,1,2010-12-01 13:17:00,2.10,15525,United Kingdom
1153,536528,85114B,IVORY ENCHANTED FOREST PLACEMAT,1,2010-12-01 13:17:00,1.65,15525,United Kingdom
1159,536528,22584,PACK OF 6 PANNETONE GIFT BOXES,2,2010-12-01 13:17:00,2.55,15525,United Kingdom
1165,536528,22911,PAPER CHAIN KIT LONDON,1,2010-12-01 13:17:00,2.95,15525,United Kingdom
1166,536528,22743,MAKE YOUR OWN FLOWERPOWER CARD KIT,1,2010-12-01 13:17:00,2.95,15525,United Kingdom
1167,536528,22744,MAKE YOUR OWN MONSOON CARD KIT,2,2010-12-01 13:17:00,2.95,15525,United Kingdom
1169,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525,United Kingdom
1172,536528,84985A,SET OF 72 GREEN PAPER DOILIES,1,2010-12-01 13:17:00,1.45,15525,United Kingdom
1179,536528,22839,3 TIER CAKE TIN GREEN AND CREAM,1,2010-12-01 13:17:00,14.95,15525,United Kingdom
1205,536530,22097,SWALLOW SQUARE TISSUE BOX,1,2010-12-01 13:21:00,1.25,17905,United Kingdom
1222,536531,21498,RED RETROSPOT WRAP,25,2010-12-01 13:23:00,0.42,15485,United Kingdom

In [28]:
# there are 36 duplicates
print(df.duplicated().sum())

36

In [29]:
# remove them - MISTAKE HERE IT DROPS THEM IN PLACE
df.drop_duplicates()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
1438,536542,20711,JUMBO BAG TOYS,20,2010-12-01 14:11:00,1.95,16456,United Kingdom
1439,536542,20713,JUMBO BAG OWLS,30,2010-12-01 14:11:00,1.95,16456,United Kingdom
1440,536542,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 14:11:00,2.95,16456,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,1,2010-12-01 14:30:00,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,2,2010-12-01 14:30:00,0.85,17841,United Kingdom

In [30]:
print(df.duplicated().sum())

36

In [31]:
df[df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897,United Kingdom
1061,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012,United Kingdom
1067,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012,United Kingdom
1140,536528,22865,HAND WARMER OWL DESIGN,1,2010-12-01 13:17:00,2.10,15525,United Kingdom
1153,536528,85114B,IVORY ENCHANTED FOREST PLACEMAT,1,2010-12-01 13:17:00,1.65,15525,United Kingdom
1159,536528,22584,PACK OF 6 PANNETONE GIFT BOXES,2,2010-12-01 13:17:00,2.55,15525,United Kingdom
1165,536528,22911,PAPER CHAIN KIT LONDON,1,2010-12-01 13:17:00,2.95,15525,United Kingdom
1166,536528,22743,MAKE YOUR OWN FLOWERPOWER CARD KIT,1,2010-12-01 13:17:00,2.95,15525,United Kingdom
1167,536528,22744,MAKE YOUR OWN MONSOON CARD KIT,2,2010-12-01 13:17:00,2.95,15525,United Kingdom
1169,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525,United Kingdom
1172,536528,84985A,SET OF 72 GREEN PAPER DOILIES,1,2010-12-01 13:17:00,1.45,15525,United Kingdom
1179,536528,22839,3 TIER CAKE TIN GREEN AND CREAM,1,2010-12-01 13:17:00,14.95,15525,United Kingdom
1205,536530,22097,SWALLOW SQUARE TISSUE BOX,1,2010-12-01 13:21:00,1.25,17905,United Kingdom
1222,536531,21498,RED RETROSPOT WRAP,25,2010-12-01 13:23:00,0.42,15485,United Kingdom

In [32]:
df = df.drop_duplicates()

In [33]:
df[df.duplicated()]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [34]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
1438,536542,20711,JUMBO BAG TOYS,20,2010-12-01 14:11:00,1.95,16456,United Kingdom
1439,536542,20713,JUMBO BAG OWLS,30,2010-12-01 14:11:00,1.95,16456,United Kingdom
1440,536542,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 14:11:00,2.95,16456,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,1,2010-12-01 14:30:00,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,2,2010-12-01 14:30:00,0.85,17841,United Kingdom

In [35]:
df['InvoiceDate'].unique()

<DatetimeArray>
['2010-12-01 08:26:00', '2010-12-01 08:28:00', '2010-12-01 08:34:00',
 '2010-12-01 08:35:00', '2010-12-01 08:45:00', '2010-12-01 09:00:00',
 '2010-12-01 09:01:00', '2010-12-01 09:02:00', '2010-12-01 09:09:00',
 '2010-12-01 09:32:00', '2010-12-01 09:34:00', '2010-12-01 09:37:00',
 '2010-12-01 09:41:00', '2010-12-01 09:45:00', '2010-12-01 09:49:00',
 '2010-12-01 09:53:00', '2010-12-01 09:56:00', '2010-12-01 09:57:00',
 '2010-12-01 09:58:00', '2010-12-01 09:59:00', '2010-12-01 10:03:00',
 '2010-12-01 10:19:00', '2010-12-01 10:24:00', '2010-12-01 10:29:00',
 '2010-12-01 10:37:00', '2010-12-01 10:39:00', '2010-12-01 10:47:00',
 '2010-12-01 10:51:00', '2010-12-01 10:52:00', '2010-12-01 10:53:00',
 '2010-12-01 11:21:00', '2010-12-01 11:22:00', '2010-12-01 11:27:00',
 '2010-12-01 11:29:00', '2010-12-01 11:32:00', '2010-12-01 11:33:00',
 '2010-12-01 11:34:00', '2010-12-01 11:41:00', '2010-12-01 11:45:00',
 '2010-12-01 11:49:00', '2010-12-01 11:57:00', '2010-12-01 11:58:00',
 '2010-12-01 12:03:00', '2010-12-01 12:08:00', '2010-12-01 12:12:00',
 '2010-12-01 12:15:00', '2010-12-01 12:22:00', '2010-12-01 12:23:00',
 '2010-12-01 12:27:00', '2010-12-01 12:31:00', '2010-12-01 12:35:00',
 '2010-12-01 12:36:00', '2010-12-01 12:38:00', '2010-12-01 12:40:00',
 '2010-12-01 12:43:00', '2010-12-01 12:48:00', '2010-12-01 12:49:00',
 '2010-12-01 12:50:00', '2010-12-01 12:51:00', '2010-12-01 12:54:00',
 '2010-12-01 12:58:00', '2010-12-01 13:04:00', '2010-12-01 13:17:00',
 '2010-12-01 13:20:00', '2010-12-01 13:21:00', '2010-12-01 13:23:00',
 '2010-12-01 13:24:00', '2010-12-01 13:31:00', '2010-12-01 13:33:00',
 '2010-12-01 13:38:00', '2010-12-01 13:45:00', '2010-12-01 13:51:00',
 '2010-12-01 13:54:00', '2010-12-01 14:03:00', '2010-12-01 14:05:00',
 '2010-12-01 14:11:00', '2010-12-01 14:30:00']
Length: 77, dtype: datetime64[ns]

In [36]:
df["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE'], dtype=object)

In [37]:
df[df["Country"]=="EIRE"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1404,536540,22968,ROSE COTTAGE KEEPSAKE BOX,4,2010-12-01 14:05:00,9.95,14911,EIRE
1405,536540,85071A,BLUE CHARLIE+LOLA PERSONAL DOORSIGN,6,2010-12-01 14:05:00,2.95,14911,EIRE
1406,536540,85071C,"CHARLIE+LOLA""EXTREMELY BUSY"" SIGN",6,2010-12-01 14:05:00,2.55,14911,EIRE
1407,536540,22355,CHARLOTTE BAG SUKI DESIGN,50,2010-12-01 14:05:00,0.85,14911,EIRE
1408,536540,21579,LOLITA DESIGN COTTON TOTE BAG,6,2010-12-01 14:05:00,2.25,14911,EIRE
1409,536540,21576,LETS GO SHOPPING COTTON TOTE BAG,6,2010-12-01 14:05:00,2.25,14911,EIRE
1410,536540,22147,FELTCRAFT BUTTERFLY HEARTS,12,2010-12-01 14:05:00,1.45,14911,EIRE
1411,536540,22150,3 STRIPEY MICE FELTCRAFT,12,2010-12-01 14:05:00,1.95,14911,EIRE
1412,536540,22492,MINI PAINT SET VINTAGE,36,2010-12-01 14:05:00,0.65,14911,EIRE
1413,536540,22493,PAINT YOUR OWN CANVAS SET,24,2010-12-01 14:05:00,1.65,14911,EIRE
1414,536540,21833,CAMOUFLAGE LED TORCH,12,2010-12-01 14:05:00,1.69,14911,EIRE
1415,536540,85135B,BLUE DRAGONFLY HELICOPTER,2,2010-12-01 14:05:00,7.95,14911,EIRE
1416,536540,85136A,YELLOW SHARK HELICOPTER,2,2010-12-01 14:05:00,7.95,14911,EIRE
1417,536540,85136C,RED SHARK HELICOPTER,2,2010-12-01 14:05:00,7.95,14911,EIRE
1418,536540,21055,TOOL BOX SOFT TOY,4,2010-12-01 14:05:00,8.95,14911,EIRE
1419,536540,21056,DOCTOR'S BAG SOFT TOY,4,2010-12-01 14:05:00,8.95,14911,EIRE
1420,536540,21889,WOODEN BOX OF DOMINOES,24,2010-12-01 14:05:00,1.25,14911,EIRE
1421,536540,21891,TRADITIONAL WOODEN SKIPPING ROPE,12,2010-12-01 14:05:00,1.25,14911,EIRE
1422,536540,22622,BOX OF VINTAGE ALPHABET BLOCKS,6,2010-12-01 14:05:00,9.95,14911,EIRE
1423,536540,C2,CARRIAGE,1,2010-12-01 14:05:00,50.00,14911,EIRE
1424,536541,21915,RED HARMONICA IN BOX,12,2010-12-01 14:05:00,1.25,14911,EIRE

In [38]:
# We change EIRE to Ireland
df["Country"] = df["Country"].replace("EIRE", "Ireland")

In [39]:
df["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'Ireland'], dtype=object)

In [40]:
# Add new column after the unipricw column: total = quantity * unitprice
df.insert(6, "TotalAmount", df["Quantity"] * df["UnitPrice"])

In [41]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,TotalAmount,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,15.30,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,22.00,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
...,...,...,...,...,...,...,...,...,...
1438,536542,20711,JUMBO BAG TOYS,20,2010-12-01 14:11:00,1.95,39.00,16456,United Kingdom
1439,536542,20713,JUMBO BAG OWLS,30,2010-12-01 14:11:00,1.95,58.50,16456,United Kingdom
1440,536542,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 14:11:00,2.95,94.40,16456,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,1,2010-12-01 14:30:00,2.10,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,2,2010-12-01 14:30:00,0.85,1.70,17841,United Kingdom

In [42]:
# FINAL clean_df to be transfered into the database
clean_df = df.copy()

In [43]:
clean_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,TotalAmount,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,15.30,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,22.00,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
...,...,...,...,...,...,...,...,...,...
1438,536542,20711,JUMBO BAG TOYS,20,2010-12-01 14:11:00,1.95,39.00,16456,United Kingdom
1439,536542,20713,JUMBO BAG OWLS,30,2010-12-01 14:11:00,1.95,58.50,16456,United Kingdom
1440,536542,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 14:11:00,2.95,94.40,16456,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,1,2010-12-01 14:30:00,2.10,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,2,2010-12-01 14:30:00,0.85,1.70,17841,United Kingdom

In [47]:
# round the total_amount column so that we don't have many decimal points.
clean_df["TotalAmount"] = df["TotalAmount"].round(2)

In [48]:
clean_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,TotalAmount,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,15.30,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,22.00,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,20.34,17850,United Kingdom
...,...,...,...,...,...,...,...,...,...
1438,536542,20711,JUMBO BAG TOYS,20,2010-12-01 14:11:00,1.95,39.00,16456,United Kingdom
1439,536542,20713,JUMBO BAG OWLS,30,2010-12-01 14:11:00,1.95,58.50,16456,United Kingdom
1440,536542,85123A,WHITE HANGING HEART T-LIGHT HOLDER,32,2010-12-01 14:11:00,2.95,94.40,16456,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,1,2010-12-01 14:30:00,2.10,2.10,17841,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,2,2010-12-01 14:30:00,0.85,1.70,17841,United Kingdom

In [50]:
# create new clean_csv to take it into the loading phase
clean_df.to_csv("clean_data.csv", index=False)